public class tryCatch {

    public static void main(String[] args) {


        try {

            int a[] = {2, 3, 4, 5};
            System.out.println(a[5]);// this is where we get the exception

        } catch (Exception e) {

            // System.out.println("There is an error and pass it on now!");// this is the message you can pass it to non technical people.

        }

    }

}

